### ISSUE TITLE
Joystick does not report pressed state

### ISSUE THREAD

**Issue by N0TB0T** [invoklab/InvokController#5]
If you lift your finger at any position, joystick does neither return to 0,0 nor does it report the lifted finger via an event or flag. Maybe i'm missing something, but isn't that essential for any joystick application?

Simply checking for a timeout in the script won't work; it seems data is only sent on change, so the behaviour of a non moving and a no longer existent touch point is the same...

**Comment by invoklab** [comment]
Hi, 

The default behaviour is that the pointer will return to center when there is no touch registered on the screen.

Yes you are correct, the app will only send data to the ESP on change, so if there is no data send, you can assume that the pointer is at the center, i.e. at (0,0). This is because the pointer will always return to center on touch release. 

I'll check if there's any bugs causing the pointer not to return to center or set the value of X and Y to non zero value on touch release.

**Comment by N0TB0T** [comment]
Actually, if there's no data send, I can not assume the pointer is at 0,0 - because if I got my finger on 0,100 or elsewhere and do not move, it's the same behaviour. So, atm the controlled vehicle will either stutter, because it only drives on changes, or it will keep on driving no matter what until I interrupt the connection.

The pointer itself may return to 0,0 - looks like it does, but it seems that does not trigger an event. Which would be all I'm asking. ;) Even though some flag for TOUCH/NO TOUCH would be a cleaner way, as that would represent different user interaction.

**Comment by invoklab** [comment]
My bad, if there's no data send, you can assume that the current X and Y is the last XY you received from the app. One thing that you can do is to set a loop to watch for variable change. This way, even if there's no data send from the app, you could still use the previous X and Y value to control your vehicle. 

For the case of "Driving no matter what until i interrupt the connection" does this happen even after you lift your finger? Because if you lift your finger, the pointer will return to the center, and will send (0,0) to the ESP, which you can use this value to stop the driving effort. 

However there are some cases where the connection drops, before the app is able to send (0,0) to the ESP, which in this case, even if the pointer returns to the center, the ESP will not be getting the newest value. You'll need to check if the websocket connection is active (green dot on top right corner).

The constant data transmission from the App to the ESP was actually implemented before, though unreleased. I thought that it will be better for the ESP to detect for value changes, and reset everything to 0 in case of connection drop, instead of relying on constant data transmission from the App. 

I'll try to add this Touch / No touch flag in the next update.

**Comment by N0TB0T** [comment]
"...if you lift your finger, the pointer will return to the center, and will send (0,0) to the ESP, which you can use this value to stop the driving effort." --> I can not confirm that. Even with the connection being stable and established, I won't get any notification of the pointer returning to 0,0. Last message sent always contains the last active position before lifting my finger, and never 0,0.

**Comment by N0TB0T** [comment]
I finally debugged it on several of my other ESPs, and it seems that in fact the connection aborting was the problem. So don't waste your time on this, all correct on your side. Thanks for the effort, and if you could consider adding the touch flag (oh, and a few more buttons in joystick mode? ;) ) I'd be super happy.

**Comment by invoklab** [comment]
I'm glad that you've figured it out and stay tune for the next update! Please let me know if you have any further questions or issues.
